# Generated by Django 4.1.4 on 2022-12-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('phone_prefix', models.CharField(max_length=10)),
                ('tag', models.CharField(max_length=100)),
                ('customer_time_zone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_launch_date', models.DateField()),
                ('end_launch_date', models.DateField()),
                ('customer_filter', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
