# Generated by Django 4.1.4 on 2022-12-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_remove_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='end_launch_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='start_launch_date',
            field=models.DateTimeField(),
        ),
    ]
